name: build-for-release

on:
  release:
    types: [published]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        include:
        - os: "ubuntu-22.04"
          os-name: "linux"
          ext: ""
        - os: "windows-2022"
          os-name: "windows"
          ext: ".exe"

    runs-on: "${{matrix.os}}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Binary
        run: "make EXE=aurora-${{github.ref_name}}-${{matrix.os-name}}"
      - name: Upload Binary to Release
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          asset_paths: '["aurora-${{github.ref_name}}-${{matrix.os-name}}${{matrix.ext}}"]'
